application.name=TRASLADO_EXTRACCION_SOACHA


aws.ssm.db.sirep.url=${DB_URL_SIREP}
aws.ssm.db.sirep.username=${DB_USERNAME_SIREP}
aws.ssm.db.sirep.password=${DB_PASSWORD_SIREP}

aws.ssm.db.traslado.url=${DB_URL_TRASLADO}
aws.ssm.db.traslado.username=${DB_USERNAME_TRASLADO}
aws.ssm.db.traslado.password=${DB_PASSWORD_TRASLADO}

aws.sqs.queue.url=${SQS_QUEUE_URL}

aws.ssm.auth.method.ps=0
aws.region=us-east-1
aws.access.key=NA
aws.secret.key=NA

traslado.parameter.type.state = ESTADO
traslado.parameter.type.limitmaxprocess = LIMTE_MAXIMO_MATRICULAS_A_PROCESAR
traslado.parameter.type.enabledAuthSqs = HABILITA_AUTENTICACION_AWS_SQS
traslado.parameter.type.enabledAuthPs = HABILITA_AUTENTICACION_AWS_PS
traslado.parameter.value.statePendiente = PENDIENTE
traslado.parameter.value.stateTransladado = TRASLADADO
traslado.parameter.value.stateCancelado = COMPLETADO
traslado.parameter.value.stateError = ERROR
traslado.parameter.value.stateIncompleto = INCOMPLETO
enrollments.sirep.allowedStates= 24MA,47IA

