# AWS
aws.region=us-east-1
aws.access.key=${ACCESS_KEY}
aws.secret.key=${SECRET_KEY}
aws.sqs.queue.url=${SQS_QUEUE_URL}
aws.sqs.enrollment.queue.url=${SQS_ENROLLMENT_QUEUE_URL}

# Datasource SIREP
sirep.datasource.url=jdbc:db2://...
sirep.datasource.username=${SIREP_USERNAME}
sirep.datasource.password=${SIREP_PASSWORD}
sirep.datasource.driver=com.ibm.db2.jcc.DB2Driver
sirep.datasource.schema=...

# Datasource TRASLADO
traslado.datasource.url=jdbc:postgresql://...
traslado.datasource.username=${TRASLADO_USERNAME}
traslado.datasource.password=${TRASLADO_PASSWORD}
traslado.datasource.driver=org.postgresql.Driver
traslado.datasource.schema=...

# Parameters
traslado.parameter.type.state=...
traslado.parameter.type.limitmaxprocess=LIMIT_MAX_PROCESS
traslado.parameter.type.enabledAuthSqs=...
traslado.parameter.value.statePendiente=...
traslado.parameter.value.stateTransladado=...
traslado.parameter.value.stateCancelado=...
traslado.parameter.value.stateError=...
traslado.parameter.value.stateIncompleto=...
